---
version: '3.8'
services:
  tradeui:
    build:
      context: .
      dockerfile: "./Dockerfile"
    image: tradeui
    # image: khulnasoft/tradeui:main
    restart: unless-stopped
    ports:
      - "3000:80"
